version: '3.8'

services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: chatServer
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
    depends_on:
      - postgres
    volumes:
      - ./server:/server
      - /server/node_modules

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
